---
R1:
    hostname: 192.168.1.201
    platform: ios
    groups:
      - cisco_group
R2:
    hostname: 192.168.1.202
    platform: ios
    groups:
      - cisco_group
R3:
    hostname: 192.168.1.203
    platform: ios
    groups:
      - cisco_group
R4:
    hostname: 192.168.1.214
    platform: ios
    groups:
      - cisco_group
R5:
    hostname: 192.168.1.205
    platform: ios
    groups:
      - cisco_group
R6:
    hostname: 192.168.1.206
    platform: ios
    groups:
      - cisco_group
R7:
    hostname: 192.168.1.207
    platform: ios
    groups:
      - cisco_group
R8:
    hostname: 192.168.1.208
    platform: ios
    groups:
      - cisco_group
